// Extraído do checklist real de captação da equipe (CHECKLIST CAPTAÇÃO.xlsx) —
// usado só como atalho de preenchimento rápido de nome de item, não é catálogo.

export const ACESSORIOS_PADRAO = [
  'Carreta',
  'Capa',
  'Fechamento Frontal',
  'Fechamento de Popa',
  'Churrasqueira',
  'Geladeira',
  'Freezer',
  'Boiler',
  'GPS',
  'Carta Náutica',
  'Sonda',
  'Rádio VHF',
  'Radar',
  'Piloto Automático',
  'AIS',
  'Dock Station',
  'Carregador de Baterias',
  'Transformador',
  'Inversor',
  'Chuveiro de Popa',
  'Chuveiro de Proa',
  'Plataforma Hidráulica',
  'Luz Subaquática',
  'Flap',
  'Zipwake',
  'Bombas de Porão',
  'Bomba Pressurizadora',
  'Tipo de Piso',
  'Farol',
  'Guincho',
  'Sistema de Som',
  'Strobo',
  'Refletor de Radar',
  'Baterias de Motor',
  'Baterias de Serviços',
  'Escada de Popa',
  'Espaço Gourmet',
  'TV',
  'Internet',
  'Vaso Sanitário',
] as const

export const ESTADO_GERAL_ITENS_PADRAO = [
  'Costado',
  'Fundo',
  'Verdugo',
  'Vidros',
  'Capotaria',
  'Estofamento',
  'Carreta',
  'Capa',
  'Porão',
  'Piso',
  'Móveis',
  'Inox',
  'Luzes de Navegação',
  'Sistema de Iluminação',
  'Acrílicos',
] as const
