alter table parceiros add column codigo bigint generated by default as identity;
alter table parceiros add constraint parceiros_codigo_unique unique (codigo);

alter table parceiros add column categoria text not null default 'outro'
  check (categoria in ('marinheiro', 'tecnico', 'proprietario', 'outro'));
alter table parceiros add column especialidade text;

-- campos exclusivos de marinheiro
alter table parceiros add column habilitacao text
  check (habilitacao in ('Amador', 'Arrais-Amador', 'Mestre Amador', 'Capitão Amador'));
alter table parceiros add column regiao_atuacao text;
alter table parceiros add column fins_de_semana_livres boolean;
alter table parceiros add column regime_trabalho text
  check (regime_trabalho in ('CLT', 'MEI', 'Autônomo', 'Outro'));

-- campos exclusivos de técnico (mecânico, eletricista, laminador, pintor, tapeceiro, marceneiro...)
alter table parceiros add column marcas_autorizadas jsonb not null default '[]'::jsonb;
alter table parceiros add column tipos_equipamento_autorizados jsonb not null default '[]'::jsonb;

-- vínculo de proprietário com uma ou mais embarcações
create table parceiro_embarcacoes (
  parceiro_id uuid not null references parceiros(id) on delete cascade,
  embarcacao_id uuid not null references embarcacoes(id) on delete cascade,
  empresa_id uuid not null references empresas(id) default auth_empresa_id(),
  criado_em timestamptz not null default now(),
  primary key (parceiro_id, embarcacao_id)
);
alter table parceiro_embarcacoes enable row level security;
create policy tenant_read_write_parceiro_embarcacoes on parceiro_embarcacoes
  for all using (empresa_id = auth_empresa_id());
revoke all on parceiro_embarcacoes from anon;
create trigger trg_sync_empresa_id before insert or update of parceiro_id
  on parceiro_embarcacoes for each row execute function sync_empresa_id('parceiros', 'parceiro_id');
